---
# This playbook installs LibreOffice

- name: Install packages
  dnf: name={{ item }} state=latest
  with_items:
    - libreoffice
    - libreoffice-langpack-pl
    - libreoffice-calc
    - libreoffice-impress
    - libreoffice-writer
    - libreoffice-draw
