---
# This playbook installs libvirt

- name: Install required packages
  dnf: name={{ item }} state=latest
  with_items:
    - libvirt
    - libvirt-python
    - virt-top
    - qemu-kvm

- name: Enable libvirt service
  service: >
    name=libvirtd
    state=started
    enabled=yes
