---
# This playbook installs Wireshark

- name: Install packages
  dnf: name={{ item }} state=latest
  with_items:
    - wireshark
    - wireshark-gnome

- name: Add user to wireshark group
  command: usermod -a -G wireshark {{ user }}
