---
# This playbook installs edshift-GTK on Fedora

- name: Install pkgs
  dnf: name=redshift-gtk state=present

# check https://github.com/jonls/redshift/issues/158 for details
- name: Create fragments directory
  file: >
    path=/etc/geoclue/fragments
    state=directory
    owner=root
    group=root
    serole=object_r
    setype=etc_t
    seuser=system_u

- name: Copy redshift related geoprovider config part
  copy: >
    src=redshift.conf
    dest=/etc/geoclue/fragments/redshift.conf
    owner=root
    group=root

- name: Is geoclue fragment copied already?
  stat: >
    path=/etc/geoclue/fragments/geoclue.conf
  register: geoclue_fragment_stat

- name: Copy geoclue original config to fragments dir
  command: cp /etc/geoclue/geoclue.conf /etc/geoclue/fragments/geoclue.conf
  when: geoclue_fragment_stat.stat.exists == false

- name: Fix for bug with geoprovider2
  assemble: >
    src=/etc/geoclue/fragments
    dest=/etc/geoclue/geoclue.conf
    group=root
    owner=root
    serole=object_r
    setype=etc_t
    seuser=system_u
