---
# This playbook installs nixnote - evernote client for linux
# For now i'm using 2.x beta as it rocks regarding performance

- name: Download package
  get_url: >
    dest={{ temp_dir }}/nixnote.rpm
    url="http://downloads.sourceforge.net/project/nevernote/NixNote2%20-%20Beta%207/nixnote2-2.0_beta7-0.x86_64.rpm?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fnevernote%2Ffiles%2FNixNote2%2520-%2520Beta%25207%2F&ts=1457869074&use_mirror=netix"

- name: Install pkg
  dnf: >
    name={{ temp_dir }}/nixnote.rpm
    state=present
