---
# This playbook installs nixnote - evernote client for linux
# For now i'm using 2.x beta as it rocks regarding performance

# dnf module cannot manage COPR repos :(
- name: Enable COPR repo
  shell: dnf copr enable nunodias/nixnote2 -y

- name: Install pkg
  dnf: >
    name=nixnote2
    state=latest
