---
- name: Install Slack client from npm
  npm: >
    name=plaidchat
    global=yes
    state=present

- name: Add entry to Gnome3 applications
  template:
    src=templates/slack.desktop
    dest={{ home_dir }}/.local/share/applications/slack.desktop
    mode=0600
    owner=docent
    group=docent
