---
- name: Install Slack client
  dnf: >
    name=https://downloads.slack-edge.com/linux_releases/slack-2.3.3-0.1.fc21.x86_64.rpm
    state=present

- name: Add entry to Gnome3 applications
  template:
    src=templates/slack.desktop
    dest={{ home_dir }}/.local/share/applications/slack.desktop
    mode=0600
    owner=docent
    group=docent
